apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-react-app
  labels:
    app: test-react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-react-app
      tier: frontend
  template:
    metadata:
      labels:
        app: test-react-app
        tier: frontend
    spec:
      containers:
      - name: testapp
        image: localhost:5000/testapp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-react-app
  labels:
    app: test-react-app
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: test-react-app
    tier: frontend
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-react-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: test-react-app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-react-app
                port:
                  number: 80